// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: content_security/content_security.proto

package content_security

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文本审核请求
type TextModerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                // 待审核的文本内容（需要base64编码）
	BizType       string                 `protobuf:"bytes,2,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"` // 业务类型，默认 "default"
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID，用于追踪
	DataId        string                 `protobuf:"bytes,4,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`    // 数据ID，用于追踪（如会话ID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextModerationRequest) Reset() {
	*x = TextModerationRequest{}
	mi := &file_content_security_content_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextModerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextModerationRequest) ProtoMessage() {}

func (x *TextModerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_security_content_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextModerationRequest.ProtoReflect.Descriptor instead.
func (*TextModerationRequest) Descriptor() ([]byte, []int) {
	return file_content_security_content_security_proto_rawDescGZIP(), []int{0}
}

func (x *TextModerationRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextModerationRequest) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *TextModerationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TextModerationRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

// 文本审核响应
type TextModerationResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Code          int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                       // 业务错误码，0 表示成功
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // 错误信息
	Suggestion    string                  `protobuf:"bytes,3,opt,name=suggestion,proto3" json:"suggestion,omitempty"`                            // 建议操作：Pass-通过 Block-违规 Review-疑似
	Label         string                  `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`                                      // 恶意标签：Normal-正常 Porn-色情 Abuse-谩骂 Ad-广告 等
	Score         int32                   `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`                                     // 恶意置信度 0-100
	DetailResults []*TextModerationDetail `protobuf:"bytes,6,rep,name=detail_results,json=detailResults,proto3" json:"detail_results,omitempty"` // 详细结果
	RequestId     string                  `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`             // 腾讯云请求ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextModerationResponse) Reset() {
	*x = TextModerationResponse{}
	mi := &file_content_security_content_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextModerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextModerationResponse) ProtoMessage() {}

func (x *TextModerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_security_content_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextModerationResponse.ProtoReflect.Descriptor instead.
func (*TextModerationResponse) Descriptor() ([]byte, []int) {
	return file_content_security_content_security_proto_rawDescGZIP(), []int{1}
}

func (x *TextModerationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TextModerationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TextModerationResponse) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *TextModerationResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TextModerationResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TextModerationResponse) GetDetailResults() []*TextModerationDetail {
	if x != nil {
		return x.DetailResults
	}
	return nil
}

func (x *TextModerationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 文本审核详细结果
type TextModerationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`           // 恶意标签
	Suggestion    string                 `protobuf:"bytes,2,opt,name=suggestion,proto3" json:"suggestion,omitempty"` // 建议操作
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`     // 命中的关键词
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`          // 置信度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextModerationDetail) Reset() {
	*x = TextModerationDetail{}
	mi := &file_content_security_content_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextModerationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextModerationDetail) ProtoMessage() {}

func (x *TextModerationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_content_security_content_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextModerationDetail.ProtoReflect.Descriptor instead.
func (*TextModerationDetail) Descriptor() ([]byte, []int) {
	return file_content_security_content_security_proto_rawDescGZIP(), []int{2}
}

func (x *TextModerationDetail) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TextModerationDetail) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *TextModerationDetail) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *TextModerationDetail) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 图片审核请求
type ImageModerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`             // 图片URL（与file_content二选一）
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // 图片内容（base64编码后的bytes）
	BizType       string                 `protobuf:"bytes,3,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`             // 业务类型，默认 "default"
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户ID
	DataId        string                 `protobuf:"bytes,5,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`                // 数据ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageModerationRequest) Reset() {
	*x = ImageModerationRequest{}
	mi := &file_content_security_content_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageModerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageModerationRequest) ProtoMessage() {}

func (x *ImageModerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_security_content_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageModerationRequest.ProtoReflect.Descriptor instead.
func (*ImageModerationRequest) Descriptor() ([]byte, []int) {
	return file_content_security_content_security_proto_rawDescGZIP(), []int{3}
}

func (x *ImageModerationRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *ImageModerationRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ImageModerationRequest) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *ImageModerationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImageModerationRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

// 图片审核响应
type ImageModerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 业务错误码，0 表示成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 错误信息
	Suggestion    string                 `protobuf:"bytes,3,opt,name=suggestion,proto3" json:"suggestion,omitempty"`                // 建议操作：Pass-通过 Block-违规 Review-疑似
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`                          // 恶意标签
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`                         // 恶意置信度 0-100
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 腾讯云请求ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageModerationResponse) Reset() {
	*x = ImageModerationResponse{}
	mi := &file_content_security_content_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageModerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageModerationResponse) ProtoMessage() {}

func (x *ImageModerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_security_content_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageModerationResponse.ProtoReflect.Descriptor instead.
func (*ImageModerationResponse) Descriptor() ([]byte, []int) {
	return file_content_security_content_security_proto_rawDescGZIP(), []int{4}
}

func (x *ImageModerationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ImageModerationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ImageModerationResponse) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *ImageModerationResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ImageModerationResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ImageModerationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_content_security_content_security_proto protoreflect.FileDescriptor

const file_content_security_content_security_proto_rawDesc = "" +
	"\n" +
	"'content_security/content_security.proto\x12#trpc.elysia.access.content_security\"~\n" +
	"\x15TextModerationRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bbiz_type\x18\x02 \x01(\tR\abizType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x17\n" +
	"\adata_id\x18\x04 \x01(\tR\x06dataId\"\x93\x02\n" +
	"\x16TextModerationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x03 \x01(\tR\n" +
	"suggestion\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12`\n" +
	"\x0edetail_results\x18\x06 \x03(\v29.trpc.elysia.access.content_security.TextModerationDetailR\rdetailResults\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"~\n" +
	"\x14TextModerationDetail\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x02 \x01(\tR\n" +
	"suggestion\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\"\xa3\x01\n" +
	"\x16ImageModerationRequest\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\x12\x19\n" +
	"\bbiz_type\x18\x03 \x01(\tR\abizType\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x17\n" +
	"\adata_id\x18\x05 \x01(\tR\x06dataId\"\xb2\x01\n" +
	"\x17ImageModerationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x03 \x01(\tR\n" +
	"suggestion\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId2\xb7\x02\n" +
	"\x16ContentSecurityService\x12\x8b\x01\n" +
	"\x0eTextModeration\x12:.trpc.elysia.access.content_security.TextModerationRequest\x1a;.trpc.elysia.access.content_security.TextModerationResponse\"\x00\x12\x8e\x01\n" +
	"\x0fImageModeration\x12;.trpc.elysia.access.content_security.ImageModerationRequest\x1a<.trpc.elysia.access.content_security.ImageModerationResponse\"\x00B8Z6github.com/yzf120/elysia-access/proto/content_securityb\x06proto3"

var (
	file_content_security_content_security_proto_rawDescOnce sync.Once
	file_content_security_content_security_proto_rawDescData []byte
)

func file_content_security_content_security_proto_rawDescGZIP() []byte {
	file_content_security_content_security_proto_rawDescOnce.Do(func() {
		file_content_security_content_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_security_content_security_proto_rawDesc), len(file_content_security_content_security_proto_rawDesc)))
	})
	return file_content_security_content_security_proto_rawDescData
}

var file_content_security_content_security_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_content_security_content_security_proto_goTypes = []any{
	(*TextModerationRequest)(nil),   // 0: trpc.elysia.access.content_security.TextModerationRequest
	(*TextModerationResponse)(nil),  // 1: trpc.elysia.access.content_security.TextModerationResponse
	(*TextModerationDetail)(nil),    // 2: trpc.elysia.access.content_security.TextModerationDetail
	(*ImageModerationRequest)(nil),  // 3: trpc.elysia.access.content_security.ImageModerationRequest
	(*ImageModerationResponse)(nil), // 4: trpc.elysia.access.content_security.ImageModerationResponse
}
var file_content_security_content_security_proto_depIdxs = []int32{
	2, // 0: trpc.elysia.access.content_security.TextModerationResponse.detail_results:type_name -> trpc.elysia.access.content_security.TextModerationDetail
	0, // 1: trpc.elysia.access.content_security.ContentSecurityService.TextModeration:input_type -> trpc.elysia.access.content_security.TextModerationRequest
	3, // 2: trpc.elysia.access.content_security.ContentSecurityService.ImageModeration:input_type -> trpc.elysia.access.content_security.ImageModerationRequest
	1, // 3: trpc.elysia.access.content_security.ContentSecurityService.TextModeration:output_type -> trpc.elysia.access.content_security.TextModerationResponse
	4, // 4: trpc.elysia.access.content_security.ContentSecurityService.ImageModeration:output_type -> trpc.elysia.access.content_security.ImageModerationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_content_security_content_security_proto_init() }
func file_content_security_content_security_proto_init() {
	if File_content_security_content_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_security_content_security_proto_rawDesc), len(file_content_security_content_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_security_content_security_proto_goTypes,
		DependencyIndexes: file_content_security_content_security_proto_depIdxs,
		MessageInfos:      file_content_security_content_security_proto_msgTypes,
	}.Build()
	File_content_security_content_security_proto = out.File
	file_content_security_content_security_proto_goTypes = nil
	file_content_security_content_security_proto_depIdxs = nil
}
