// Code generated by MockGen. DO NOT EDIT.
// Source: content_security.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=content_security_mock.go -package=content_security --source=content_security.trpc.go -self_package=github.com/yzf120/elysia-access/proto/content_security
//

// Package content_security is a generated GoMock package.
package content_security

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockContentSecurityServiceService is a mock of ContentSecurityServiceService interface.
type MockContentSecurityServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockContentSecurityServiceServiceMockRecorder
}

// MockContentSecurityServiceServiceMockRecorder is the mock recorder for MockContentSecurityServiceService.
type MockContentSecurityServiceServiceMockRecorder struct {
	mock *MockContentSecurityServiceService
}

// NewMockContentSecurityServiceService creates a new mock instance.
func NewMockContentSecurityServiceService(ctrl *gomock.Controller) *MockContentSecurityServiceService {
	mock := &MockContentSecurityServiceService{ctrl: ctrl}
	mock.recorder = &MockContentSecurityServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentSecurityServiceService) EXPECT() *MockContentSecurityServiceServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockContentSecurityServiceService) ISGOMOCK() struct{} {
	return struct{}{}
}

// ImageModeration mocks base method.
func (m *MockContentSecurityServiceService) ImageModeration(ctx context.Context, req *ImageModerationRequest) (*ImageModerationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageModeration", ctx, req)
	ret0, _ := ret[0].(*ImageModerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageModeration indicates an expected call of ImageModeration.
func (mr *MockContentSecurityServiceServiceMockRecorder) ImageModeration(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageModeration", reflect.TypeOf((*MockContentSecurityServiceService)(nil).ImageModeration), ctx, req)
}

// TextModeration mocks base method.
func (m *MockContentSecurityServiceService) TextModeration(ctx context.Context, req *TextModerationRequest) (*TextModerationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TextModeration", ctx, req)
	ret0, _ := ret[0].(*TextModerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TextModeration indicates an expected call of TextModeration.
func (mr *MockContentSecurityServiceServiceMockRecorder) TextModeration(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextModeration", reflect.TypeOf((*MockContentSecurityServiceService)(nil).TextModeration), ctx, req)
}

// MockContentSecurityServiceClientProxy is a mock of ContentSecurityServiceClientProxy interface.
type MockContentSecurityServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockContentSecurityServiceClientProxyMockRecorder
}

// MockContentSecurityServiceClientProxyMockRecorder is the mock recorder for MockContentSecurityServiceClientProxy.
type MockContentSecurityServiceClientProxyMockRecorder struct {
	mock *MockContentSecurityServiceClientProxy
}

// NewMockContentSecurityServiceClientProxy creates a new mock instance.
func NewMockContentSecurityServiceClientProxy(ctrl *gomock.Controller) *MockContentSecurityServiceClientProxy {
	mock := &MockContentSecurityServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockContentSecurityServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentSecurityServiceClientProxy) EXPECT() *MockContentSecurityServiceClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockContentSecurityServiceClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// ImageModeration mocks base method.
func (m *MockContentSecurityServiceClientProxy) ImageModeration(ctx context.Context, req *ImageModerationRequest, opts ...client.Option) (*ImageModerationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ImageModeration", varargs...)
	ret0, _ := ret[0].(*ImageModerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageModeration indicates an expected call of ImageModeration.
func (mr *MockContentSecurityServiceClientProxyMockRecorder) ImageModeration(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageModeration", reflect.TypeOf((*MockContentSecurityServiceClientProxy)(nil).ImageModeration), varargs...)
}

// TextModeration mocks base method.
func (m *MockContentSecurityServiceClientProxy) TextModeration(ctx context.Context, req *TextModerationRequest, opts ...client.Option) (*TextModerationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TextModeration", varargs...)
	ret0, _ := ret[0].(*TextModerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TextModeration indicates an expected call of TextModeration.
func (mr *MockContentSecurityServiceClientProxyMockRecorder) TextModeration(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextModeration", reflect.TypeOf((*MockContentSecurityServiceClientProxy)(nil).TextModeration), varargs...)
}
