// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: content_security/content_security.proto

package content_security

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ContentSecurityServiceService defines service.
type ContentSecurityServiceService interface {
	// TextModeration 文本内容安全审核
	TextModeration(ctx context.Context, req *TextModerationRequest) (*TextModerationResponse, error)
	// ImageModeration 图片内容安全审核
	ImageModeration(ctx context.Context, req *ImageModerationRequest) (*ImageModerationResponse, error)
}

func ContentSecurityServiceService_TextModeration_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &TextModerationRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ContentSecurityServiceService).TextModeration(ctx, reqbody.(*TextModerationRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ContentSecurityServiceService_ImageModeration_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ImageModerationRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ContentSecurityServiceService).ImageModeration(ctx, reqbody.(*ImageModerationRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ContentSecurityServiceServer_ServiceDesc descriptor for server.RegisterService.
var ContentSecurityServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.access.content_security.ContentSecurityService",
	HandlerType: ((*ContentSecurityServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.access.content_security.ContentSecurityService/TextModeration",
			Func: ContentSecurityServiceService_TextModeration_Handler,
		},
		{
			Name: "/trpc.elysia.access.content_security.ContentSecurityService/ImageModeration",
			Func: ContentSecurityServiceService_ImageModeration_Handler,
		},
	},
}

// RegisterContentSecurityServiceService registers service.
func RegisterContentSecurityServiceService(s server.Service, svr ContentSecurityServiceService) {
	if err := s.Register(&ContentSecurityServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ContentSecurityService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedContentSecurityService struct{}

// TextModeration 文本内容安全审核
func (s *UnimplementedContentSecurityService) TextModeration(ctx context.Context, req *TextModerationRequest) (*TextModerationResponse, error) {
	return nil, errors.New("rpc TextModeration of service ContentSecurityService is not implemented")
}

// ImageModeration 图片内容安全审核
func (s *UnimplementedContentSecurityService) ImageModeration(ctx context.Context, req *ImageModerationRequest) (*ImageModerationResponse, error) {
	return nil, errors.New("rpc ImageModeration of service ContentSecurityService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ContentSecurityServiceClientProxy defines service client proxy
type ContentSecurityServiceClientProxy interface {
	// TextModeration 文本内容安全审核
	TextModeration(ctx context.Context, req *TextModerationRequest, opts ...client.Option) (rsp *TextModerationResponse, err error)
	// ImageModeration 图片内容安全审核
	ImageModeration(ctx context.Context, req *ImageModerationRequest, opts ...client.Option) (rsp *ImageModerationResponse, err error)
}

type ContentSecurityServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewContentSecurityServiceClientProxy = func(opts ...client.Option) ContentSecurityServiceClientProxy {
	return &ContentSecurityServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ContentSecurityServiceClientProxyImpl) TextModeration(ctx context.Context, req *TextModerationRequest, opts ...client.Option) (*TextModerationResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.access.content_security.ContentSecurityService/TextModeration")
	msg.WithCalleeServiceName(ContentSecurityServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ContentSecurityService")
	msg.WithCalleeMethod("TextModeration")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &TextModerationResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ContentSecurityServiceClientProxyImpl) ImageModeration(ctx context.Context, req *ImageModerationRequest, opts ...client.Option) (*ImageModerationResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.access.content_security.ContentSecurityService/ImageModeration")
	msg.WithCalleeServiceName(ContentSecurityServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ContentSecurityService")
	msg.WithCalleeMethod("ImageModeration")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ImageModerationResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
